spring.application.name=CurdOperations

spring.datasource.url=jdbc:mysql://localhost:3306/clgadministration
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true